### ISSUE TITLE
Open Reward Task Bug

### ISSUE THREAD

**Issue by procheekibreeki** [gaby/ABS#4]
The Open Reward Task Button just loops the the Microsoft Rewards Page and doesn't actually open up the reward tasks.

**Comment by h4x0rm1k3** [comment]
I've noticed this issue on a few of my accounts now, even some new ones which are a day old! It seems that when you sign in to Bing normally it'll do the searches fine but when clicking the open reward tasks button it'll either go to a rewards login page or if you're lucky it'll go to the rewards page but will keep refreshing the page every time you click open reward tasks! The 1 thing i've noticed different is the page URL, the standard 1 will go to rewards.microsoft.com and search fine but the ones with issues will open up a URL with /?redref=amc at the end of it which seems to be messing up the function somehow and for the life of me I can't work out why, i've tried clearing the cache, VM's, different browsers, the lot and every time it'll open that same page with /?redref=amc in it!

**Comment by h4x0rm1k3** [comment]
Try this version, all i've done is alter the rewards tasks URL and altered 1 of the permissions URL's which seems to have done the trick and is working with the rewards URL that ends with /?redref=amc . It's the complete source files so you can do a diff check against the originals to see what I changed to make sure it's not been bugged etc. Link is on Mediafire as no point uploading this version when it's only for one specific issue although from testing it does work on accounts that aren't affected too because the altered URL still opens the rewards page either way and will still perform both searches and the quiz's etc. https://www.mediafire.com/file/7izuovjbebkamz5/ABS-master.rar/file

Any issues give me a shout. If it's a different URL that pops up then send me the complete URL and i'll set it for you.

**Comment by daedalus311** [comment]
I really appreciate this update.  It works like it did a few weeks ago and saves me a ton of time.

**Comment by gaby** [comment]
I'm running into the same bug, the original developer of the tool deleted the original repository. I think my fork is the only up-to-date fork that survived.

Maybe @mikeyaworski can provide some input.

**Comment by h4x0rm1k3** [comment]
> I'm running into the same bug, the original developer of the tool deleted the original repository. I think my fork is the only up-to-date fork that survived.
> 
> Maybe @mikeyaworski can provide some input.

I forked @mikeyaworski ' s version and changed the URL's in the code to match the issue that myself and some others were facing where the daily tasks weren't being done apart from the daily searches. It now works as it should do and has worked perfectly ever since I updated it nearly 2 weeks ago now. The Chrome & Firefox extensions were removed by the stores so the only way to install it now is manually.

**Comment by daedalus311** [comment]
> I'm running into the same bug, the original developer of the tool deleted the original repository. I think my fork is the only up-to-date fork that survived.
> 
> Maybe @mikeyaworski can provide some input.

As h4x said, his update works perfectly like before.  I just used it and it opens everything including the "More Activities" tasks.

**Comment by daedalus311** [comment]
Hello again h40rm1k3,

There is no "Issues" category on your ABS fork so I'll ask here:  today the rewards extension only did the search and none of the daily/optional rewards.  This is the same issue as befoire your fix.  The referral url is the same when I click the "rewards" on the extension... ?redref=amc

When I open the rewards page from the Bing Rewards Extension, though, the extension is https://rewards.microsoft.com/?pc=U523&redref=amc    I'm not sure if that's new or not, or if it even matters.

I have both your ABS (1.2.31.1 and the previous 1.2.31) and neither are working.  Any idea how to get this fixed? Thanks a ton!

**Comment by h4x0rm1k3** [comment]
Hi daedalus311,

Yes I woke up this morning and all mine weren't done either. I've been trying to work out why for a couple of hours now and can't get it to work as of yet, i've tried reverting the URL back to it's original, adding other bits to it that i've found when clicking various things to get to the rewards page and nothing so far. I'd not seen that URL you mentioned before so hunted down the extension that you mentioned and got the exact same URL you have so i'll see if adding that 1 might work later on and if it does i'll update my git and let you know by messaging you on here again. It does seem very strange 'cos I keep getting the old ?redref=amc URL when going the route I did last time to find the changed URL. It seems strange that it's roughly exactly 28 days since I/we faced this issue before so i'm guessing Microsoft are changing the URL somehow every 28 days or so.

**Comment by daedalus311** [comment]
Dang, you're a beast.   What program do you use to code these Github
projects?  I was going to go into the code and mess with it but I've never
used Github projects before.

**Comment by h4x0rm1k3** [comment]
I'm not a coder by any stretch of the imagination, I used to type out BASIC code years ago so can 'just' about follow what's going on in other code. The only thing I  use is Notepad++ to be able to read & edit code and then just uploaded it on to git once i'd tested that it was working for me. If you want to try and see if your URL will work then the part of the code you want to be looking at is in the constants.js in the src folder, if you scroll down to the end of the code you'll find this line - REWARDS_URL: 'https://rewards.microsoft.com/?pc=U523&redref=amc', just change the URL in between the two ' ' and save it, then install it to chrome as before and test if it's working.

**Comment by h4x0rm1k3** [comment]
I just tried the URL you found and it's not working still. It's strange 'cos I just made a completely new Microsoft account and didn't install the extension, clicked through to the rewards page which still gives me the old ?redref=amc URL so I don't know what's going on with it at the moment, i'm guessing that they may have changed something else which isn't allowing the clicks to register and open the clickables in the rewards tabs but I can't be completely sure about that. I'll keep working at it anyway 'cos doing the clickables for 24 accounts takes A LONG TIME!!! and I can't be arsed to do them daily manually!

**Comment by daedalus311** [comment]
lol. 24 accounts? Like two peas in a pod.  My brother and I have the same.

I'm also in the same boat: I learned some programming but never got into
the complexities. It's easy to follow the code until complex functions
start chugging.

I actually just finished all the rewards so Ill have to mess with it
tomorrow.   It does a long time to do them, haha.

**Comment by daedalus311** [comment]
I can't figure it out brother.  The mee-card in the code is the same as the webpage, so I don't see why it's not working.  No big deal.  I'll have to work with what I got for now.

**Comment by h4x0rm1k3** [comment]
@daedalus311 It's now working as it should be. I ended up having to pick the brains of another github user who'd just updated their script to find out what changed. I was staring at the right place for ages but I just couldn't put my finger on what was wrong and couldn't find it in the page source code anywhere. Sneaky little MS, lets hope this fix holds out for longer than 28 days this time!. My Git has been updated accordingly so you can grab it from there and use as normal. When updating the bot/extension make sure to refresh the rewards page 1st time else it'll work but won't open pages so you'll think it's broken still, once refreshed with the new code in place it'll work like it did before.

**Comment by daedalus311** [comment]
Man you're the best.  I spent a ton of time trying two other bots, setting
up Linux, Python, pip, selenium, geckodriver, etc, and couldn't get the
offers to work.  What did you end up changing?

And the easiest way was to close the browser and reopen to get the update
to work without hassle.

**Comment by h4x0rm1k3** [comment]
I ended up asking Daniel203 for a little help as he has his own bot (which I couldn't work out how to use!) which he'd updated recently and had the URL which changed last month in the code so picked his brains for an answer. In the end it was a simple fix and the answer was pretty much staring me in the face as I had a hunch the issue was in the open-rewards-tasks.js file but I just couldn't quite put my finger on it. All that needed to be changed was the line - clickAll('a.c-call-to-action', card);   to   clickAll('a.ds-card-sec', card);   . Now I know what to look for if it changes again in 27-28 days time i'll start there and the URL again. How it was found is to right click any of the rewards boxes and inspect, from there you can see the bit of code that needs adjusting so that the bot can again click the boxes to open the rewards tabs. 
I didn't know that closing the browser and re-opening would update the bot, seems a bit weird as it's not on the chrome store so shouldn't update that way. If by chance you mean you updated the old code to the new on your PC then yes that does seem to work but the version number in manage extensions won't change as I upped it to 1.2.31.2 because of this months update. 
No doubt next month something will change again but at least now I have a better idea of where to look and how to find the info next time so i'll keep it up to date as and when things change.

By the way, most of the other bots on Github are old and not updated so the searches will probably work but the offers won't, I used to use Microsoft-rewards-bot myself a couple of years ago which used to run perfectly until 1 day it didn't and then I didn't bother until I come across ABS and because ABS can do multiple accounts and is pretty quick I want to try and keep it going for as long as possible!

**Comment by daedalus311** [comment]
All I did was download the new version and replaced the old files.  The
first account I reloaded the extension inside Edge, but then after I
realized by closing all my browsers Edge automatically reloads the
extensions. The version updated to 1.2.31.2 when I re-opened the browser.

   If you delete the extension folder you download it will not load the
extension inside the browser..not sure if you know that.  I wanted to clean
up my folder so I deleted the download thinking Edge saves its own
extension files. Nope. It simply uses the one you give it.

Yeah none of those other programs worked for the offers.  I did learn how
to setup python, Hyper-V, and linux, though, so it wasn't a total waste of
time.

Thanks a bunch, brother.  Teamwork makes the dream work...in this case your
work makes the dream work, haha.

**Comment by h4x0rm1k3** [comment]
I don't use Edge, only Chrome which is probably why. I did notice that when making new profiles in Chrome though that when you add the unpacked extension it always uses the same directory where the files are placed and they're not copied multiple times to the appdata's Google Chrome user folder which is handy. I only know that because when I set it up for my friend he moved the folder with the files from his desktop to a different folder and the next day when he went to use it the extension was broken and he had to install it again! Glad it's all working again though for the time being as I was dreading having to do the dailies 24 times every day!

**Comment by gaby** [comment]
Fixed via #12

**Comment by h4x0rm1k3** [comment]
@gaby The rewards link you used is correct but it will change itself to 'https://rewards.microsoft.com/?redref=amc' 
So if you're updating ABS then use that link instead as it's been working for about 9+ months now without issue.

**Comment by daedalus311** [comment]
It's broken again. Trying to fix it. Hopefully, I figure it out today and I can post what I did.

**Comment by gaby** [comment]
@daedalus311 Let me know, i'm going to reopen this then

**Comment by daedalus311** [comment]
Looks like the new URL is https://rewards.bing.com/   should be an easy fix...maybe.

**Comment by daedalus311** [comment]
https://github.com/h4x0rm1k3/ABS   That guy already fixed it apparently. Im at work and can't access the files to change the URL manually at the moment.

**Comment by h4x0rm1k3** [comment]
@daedalus311 Yes it's fixed on my version, it is just all mentions of rewards.microsoft.com need changing to rewards.bing.com in both constants.js & manifest.json and then it should work again.
